export enum SystemFeature {
  REPORTING = 'REPORTING',
  INVENTORY_MANAGEMENT = 'INVENTORY_MANAGEMENT',
  SALES_POS = 'SALES_POS',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  STOCK_AUDIT = 'STOCK_AUDIT',
  SUPPLIERS = 'SUPPLIERS',
  PURCHASES = 'PURCHASES',
  EXPENSES = 'EXPENSES',
  FORECASTING = 'FORECASTING',
  CREDIT_MANAGEMENT = 'CREDIT_MANAGEMENT',
  PRESCRIPTIONS = 'PRESCRIPTIONS'
}
